In [1]:
import numpy as np

## Data Types and Attributes

In [2]:
first_nparray = np.array([2,5,8])
first_nparray

array([2, 5, 8])

In [3]:
second_nparr = np.array([7,0,1])
second_nparr

array([7, 0, 1])

## check the datatype with type(var_name)

In [4]:
type(second_nparr)

numpy.ndarray

In [5]:
type(first_nparray)

numpy.ndarray

##creating single a vector and matrix(es)

In [8]:
vec = np.array([1,2,3])
vec

array([1, 2, 3])

In [9]:
##this is a dual-dimensional array
matx1 = np.array([[1,2,2.7],[3,4,5],[5.5,6,7]])
matx1

array([[1. , 2. , 2.7],
       [3. , 4. , 5. ],
       [5.5, 6. , 7. ]])

In [31]:
##a multi-dimensional array
matx2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
matx2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## NOTE: if there's one or more float(s) in a vector or matrix, all the integers will have dots after them.

In [11]:
 first_nparray.shape

(3,)

In [12]:
second_nparr.shape

(3,)

In [13]:
matx1.shape

(3, 3)

In [14]:
matx2.shape

(3, 2, 3)

In [15]:
first_nparray.ndim, second_nparr.ndim, matx1.ndim, matx2.ndim

(1, 1, 2, 3)

In [17]:
matx3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]], [[19,20,21], [22,23,24]]])
matx3.ndim

3

In [18]:
first_nparray.dtype, second_nparr.dtype, matx1.dtype, matx2.dtype, matx3.dtype

(dtype('int32'),
 dtype('int32'),
 dtype('float64'),
 dtype('int32'),
 dtype('int32'))

In [20]:
first_nparray.size, second_nparr.size, matx1.size, matx2.size, matx3.size

(3, 3, 9, 18, 24)

In [21]:
type(first_nparray), type(second_nparr), type(matx1), type(matx2), type(matx3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [29]:
## create a DataFrame from a NumPy array

import pandas as pd

df = pd.DataFrame(first_nparray)
df1 = pd.DataFrame(second_nparr)
df2 = pd.DataFrame(matx1)


In [23]:
df

0
0  2
1  5
2  8

In [24]:
df1

0
0  7
1  0
2  1

In [38]:
df2
# df2.shape

0    1    2
0  1.0  2.0  2.7
1  3.0  4.0  5.0
2  5.5  6.0  7.0

In [36]:
# df3 = pd.DataFrame(matx2)
matx2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## Creating NumPy Arrays

In [45]:
## below will create and shape a dual-dimensional array.
arr_of_ones = np.ones((3,3), dtype=int)

In [42]:
arr_of_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
arr_of_ones.dtype

dtype('int32')