In [1]:
import numpy as np

## Data Types and Attributes

In [2]:
first_nparray = np.array([2,5,8])
first_nparray

array([2, 5, 8])

In [3]:
second_nparr = np.array([7,0,1])
second_nparr

array([7, 0, 1])

## check the datatype with type(var_name)

In [4]:
type(second_nparr)

numpy.ndarray

In [5]:
type(first_nparray)

numpy.ndarray

##creating single a vector and matrix(es)

In [6]:
vec = np.array([1,2,3])
vec

array([1, 2, 3])

In [7]:
##this is a dual-dimensional array
matx1 = np.array([[1,2,2.7],[3,4,5],[5.5,6,7]])
matx1

array([[1. , 2. , 2.7],
       [3. , 4. , 5. ],
       [5.5, 6. , 7. ]])

In [8]:
##a multi-dimensional array
matx2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
matx2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## NOTE: if there's one or more float(s) in a vector or matrix, all the integers will have dots after them.

In [9]:
 first_nparray.shape

(3,)

In [10]:
second_nparr.shape

(3,)

In [11]:
matx1.shape

(3, 3)

In [12]:
matx2.shape

(3, 2, 2)

In [13]:
first_nparray.ndim, second_nparr.ndim, matx1.ndim, matx2.ndim

(1, 1, 2, 3)

In [14]:
matx3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]], [[19,20,21], [22,23,24]]])
matx3.ndim

3

In [15]:
first_nparray.dtype, second_nparr.dtype, matx1.dtype, matx2.dtype, matx3.dtype

(dtype('int32'),
 dtype('int32'),
 dtype('float64'),
 dtype('int32'),
 dtype('int32'))

In [16]:
first_nparray.size, second_nparr.size, matx1.size, matx2.size, matx3.size

(3, 3, 9, 12, 24)

In [17]:
type(first_nparray), type(second_nparr), type(matx1), type(matx2), type(matx3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
## create a DataFrame from a NumPy array

import pandas as pd

df = pd.DataFrame(first_nparray)
df1 = pd.DataFrame(second_nparr)
df2 = pd.DataFrame(matx1)


In [19]:
df

0
0  2
1  5
2  8

In [20]:
df1

0
0  7
1  0
2  1

In [21]:
df2
# df2.shape

0    1    2
0  1.0  2.0  2.7
1  3.0  4.0  5.0
2  5.5  6.0  7.0

In [22]:
# df3 = pd.DataFrame(matx2)
matx2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## Creating NumPy Arrays

In [23]:
## below will create and shape a dual-dimensional array.
arr_of_ones = np.ones((3,3), dtype=int, order = 'F')

In [24]:
arr_of_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
arr_of_ones.dtype

dtype('int32')

In [26]:
type(arr_of_ones)

numpy.ndarray

In [27]:
arr_of_ones.dtype

dtype('int32')

In [28]:
arr_of_ones.shape

(3, 3)

In [29]:
arr_of_ones.size

9

In [30]:
arr_of_zeros = np.empty((3,2))

In [31]:
arr_of_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
arr_of_zeros.shape

(3, 2)

In [33]:
multidim_arr = np.full((1,2), [2,3])

In [34]:
multidim_arr

array([[2, 3]])

In [35]:
empty_arr = np.empty((3,3))

In [36]:
empty_arr

array([[1. , 2. , 2.7],
       [3. , 4. , 5. ],
       [5.5, 6. , 7. ]])

In [37]:
empty_arr.dtype

dtype('float64')

In [38]:
empty_arr.shape

(3, 3)

empty_arr.sise

In [39]:
empty_arr.size

9

In [40]:
range_arr = np.arange(1,12)

In [41]:
range_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
range_arr1 = np.arange(0,10,3)

In [43]:
range_arr1

array([0, 3, 6, 9])

In [44]:
rando_arr = np.random.randint(1,14, size=(3,4))

In [45]:
rando_arr

array([[ 2,  8, 10,  9],
       [11,  5,  2,  9],
       [ 1, 13,  5,  2]])

In [46]:
rand_arr = np.random.randint(10, size=6)

In [47]:
rand_arr

array([4, 8, 7, 8, 6, 9])

In [48]:
rand_arr1 = np.random.randint(20, size=(4,4), dtype=int)

In [49]:
rand_arr1

array([[ 2,  8, 10, 13],
       [ 2,  5, 17, 16],
       [14, 19, 10,  0],
       [ 4, 16,  5,  8]])

In [50]:
rand_arr1.dtype

dtype('int32')

In [51]:
rand_arr1.size

16

In [52]:
## here is another way to create random arrays
rand_arr2 = np.random.random((4,4))

In [53]:
rand_arr2

array([[0.34747057, 0.21129554, 0.35700192, 0.57996728],
       [0.46976049, 0.81352424, 0.52278181, 0.52678326],
       [0.7619495 , 0.54207736, 0.23804855, 0.97145966],
       [0.70864893, 0.79733178, 0.18883101, 0.72342139]])

In [54]:
## yet another random generating technique
rand_arr3 = np.random.rand(3,3)

In [55]:
rand_arr3

array([[0.62534365, 0.18715252, 0.32797096],
       [0.14908983, 0.32134475, 0.11622055],
       [0.53612528, 0.3835495 , 0.60511408]])

In [56]:
# pseudo random numbers
np.random.seed(seed=0)
rand_arr4 = np.random.randint(7, size=(5,3))
rand_arr4

array([[4, 5, 0],
       [3, 3, 3],
       [1, 3, 5],
       [2, 4, 6],
       [0, 0, 4]])

In [57]:
np.random.seed(seed=8)
rand_arr5 = np.random.randint(4, size=(4,3))
rand_arr5

array([[3, 0, 1],
       [1, 1, 2],
       [0, 3, 0],
       [3, 0, 1]])

## different ways of viewing arrays and matrices

In [58]:
np.unique(rand_arr5)

array([0, 1, 2, 3])

In [59]:
rand_arr5[1]

array([1, 1, 2])

In [60]:
rand_arr5[1][2]

2

In [61]:
rand_arr5

array([[3, 0, 1],
       [1, 1, 2],
       [0, 3, 0],
       [3, 0, 1]])

In [62]:
rand_arr5[:2, :2]

array([[3, 0],
       [1, 1]])

In [65]:
## create a 4-dim array
d4 = np.random.randint(7, size=(3,4,6,7))
d4

array([[[[5, 4, 1, 3, 2, 3, 4],
         [5, 1, 5, 5, 2, 3, 2],
         [6, 6, 5, 0, 1, 3, 4],
         [5, 5, 3, 2, 1, 2, 2],
         [6, 1, 5, 5, 6, 1, 3],
         [4, 3, 3, 6, 4, 5, 5]],

        [[0, 4, 4, 2, 0, 5, 2],
         [6, 4, 3, 0, 1, 4, 6],
         [3, 4, 5, 3, 2, 2, 6],
         [6, 6, 2, 6, 1, 6, 0],
         [1, 2, 6, 1, 2, 6, 2],
         [3, 3, 0, 1, 0, 0, 6]],

        [[6, 1, 4, 1, 4, 0, 2],
         [2, 0, 6, 4, 5, 2, 3],
         [3, 3, 3, 6, 4, 0, 1],
         [6, 3, 2, 0, 0, 5, 4],
         [3, 4, 3, 0, 1, 0, 3],
         [2, 1, 5, 2, 6, 6, 3]],

        [[0, 2, 1, 5, 6, 4, 4],
         [5, 1, 3, 5, 5, 4, 0],
         [0, 4, 0, 6, 0, 1, 0],
         [0, 1, 6, 5, 5, 4, 2],
         [2, 5, 6, 2, 4, 2, 6],
         [5, 2, 0, 4, 3, 2, 4]]],


       [[[1, 5, 6, 3, 3, 0, 4],
         [4, 6, 0, 4, 6, 1, 0],
         [5, 3, 4, 0, 2, 3, 2],
         [5, 2, 5, 2, 3, 6, 1],
         [6, 2, 4, 2, 1, 2, 4],
         [2, 4, 6, 3, 1, 1, 1]],

        [[3, 4, 0, 2, 0, 0, 

In [66]:
np.unique(d4)

array([0, 1, 2, 3, 4, 5, 6])

In [67]:
d4[0][0][1]

array([5, 1, 5, 5, 2, 3, 2])