In [1]:
import numpy as np

## Data Types and Attributes

In [2]:
first_nparray = np.array([2,5,8])
first_nparray

array([2, 5, 8])

In [3]:
second_nparr = np.array([7,0,1])
second_nparr

array([7, 0, 1])

## check the datatype with type(var_name)

In [4]:
type(second_nparr)

numpy.ndarray

In [5]:
type(first_nparray)

numpy.ndarray

##creating single a vector and matrix(es)

In [8]:
vec = np.array([1,2,3])
vec

array([1, 2, 3])

In [9]:
##this is a dual-dimensional array
matx1 = np.array([[1,2,2.7],[3,4,5],[5.5,6,7]])
matx1

array([[1. , 2. , 2.7],
       [3. , 4. , 5. ],
       [5.5, 6. , 7. ]])

In [31]:
##a multi-dimensional array
matx2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
matx2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## NOTE: if there's one or more float(s) in a vector or matrix, all the integers will have dots after them.

In [11]:
 first_nparray.shape

(3,)

In [12]:
second_nparr.shape

(3,)

In [13]:
matx1.shape

(3, 3)

In [14]:
matx2.shape

(3, 2, 3)

In [15]:
first_nparray.ndim, second_nparr.ndim, matx1.ndim, matx2.ndim

(1, 1, 2, 3)

In [17]:
matx3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]], [[19,20,21], [22,23,24]]])
matx3.ndim

3

In [18]:
first_nparray.dtype, second_nparr.dtype, matx1.dtype, matx2.dtype, matx3.dtype

(dtype('int32'),
 dtype('int32'),
 dtype('float64'),
 dtype('int32'),
 dtype('int32'))

In [20]:
first_nparray.size, second_nparr.size, matx1.size, matx2.size, matx3.size

(3, 3, 9, 18, 24)

In [21]:
type(first_nparray), type(second_nparr), type(matx1), type(matx2), type(matx3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [29]:
## create a DataFrame from a NumPy array

import pandas as pd

df = pd.DataFrame(first_nparray)
df1 = pd.DataFrame(second_nparr)
df2 = pd.DataFrame(matx1)


In [23]:
df

0
0  2
1  5
2  8

In [24]:
df1

0
0  7
1  0
2  1

In [38]:
df2
# df2.shape

0    1    2
0  1.0  2.0  2.7
1  3.0  4.0  5.0
2  5.5  6.0  7.0

In [36]:
# df3 = pd.DataFrame(matx2)
matx2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## Creating NumPy Arrays

In [48]:
## below will create and shape a dual-dimensional array.
arr_of_ones = np.ones((3,3), dtype=int, order = 'F')

In [49]:
arr_of_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [50]:
arr_of_ones.dtype

dtype('int32')

In [51]:
type(arr_of_ones)

numpy.ndarray

In [53]:
arr_of_ones.dtype

dtype('int32')

In [54]:
arr_of_ones.shape

(3, 3)

In [55]:
arr_of_ones.size

9

In [80]:
arr_of_zeros = np.empty((3,2))

In [81]:
arr_of_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [82]:
arr_of_zeros.shape

(3, 2)

In [83]:
multidim_arr = np.full((1,2), [2,3])

In [84]:
multidim_arr

array([[2, 3]])

In [89]:
empty_arr = np.empty((3,3))

In [90]:
empty_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [91]:
empty_arr.dtype

dtype('float64')

In [92]:
empty_arr.shape

(3, 3)

empty_arr.sise

In [93]:
empty_arr.size

9

In [95]:
range_arr = np.arange(1,12)

In [96]:
range_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
range_arr1 = np.arange(0,10,3)

In [99]:
range_arr1

array([0, 3, 6, 9])

In [108]:
rando_arr = np.random.randint(1,14, size=(3,4))

In [109]:
rando_arr

array([[10,  7,  5, 12],
       [ 6,  6, 12,  8],
       [ 7,  4,  9,  3]])

In [110]:
rand_arr = np.random.randint(10, size=6)

In [111]:
rand_arr

array([4, 8, 4, 6, 2, 8])

In [112]:
rand_arr1 = np.random.randint(20, size=(4,4), dtype=int)

In [113]:
rand_arr1

array([[ 9, 12,  1, 19],
       [ 0, 14, 16,  0],
       [19, 19,  4,  7],
       [17, 18, 14,  5]])

In [114]:
rand_arr1.dtype

dtype('int32')

In [115]:
rand_arr1.size

16

In [119]:
## here is another way to create random arrays
rand_arr2 = np.random.random((4,4))

In [120]:
rand_arr2

array([[0.25215695, 0.21823782, 0.07577535, 0.10004162],
       [0.18609353, 0.58398097, 0.8641704 , 0.77346787],
       [0.45306205, 0.91529537, 0.73931782, 0.83294033],
       [0.87640556, 0.23943006, 0.17566431, 0.65008543]])

In [121]:
## yet another random generating technique
rand_arr3 = np.random.rand(3,3, )

TypeError: rand() got an unexpected keyword argument 'dtype'