In [1]:
import numpy as np

## Data Types and Attributes

In [2]:
first_nparray = np.array([2,5,8])
first_nparray

array([2, 5, 8])

In [3]:
second_nparr = np.array([7,0,1])
second_nparr

array([7, 0, 1])

## check the datatype with type(var_name)

In [4]:
type(second_nparr)

numpy.ndarray

In [5]:
type(first_nparray)

numpy.ndarray

##creating single a vector and matrix(es)

In [6]:
vec = np.array([1,2,3])
vec

array([1, 2, 3])

In [7]:
##this is a dual-dimensional array
matx1 = np.array([[1,2,2.7],[3,4,5],[5.5,6,7]])
matx1

array([[1. , 2. , 2.7],
       [3. , 4. , 5. ],
       [5.5, 6. , 7. ]])

In [8]:
##a multi-dimensional array
matx2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
matx2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## NOTE: if there's one or more float(s) in a vector or matrix, all the integers will have dots after them.

In [9]:
 first_nparray.shape

(3,)

In [10]:
second_nparr.shape

(3,)

In [11]:
matx1.shape

(3, 3)

In [12]:
matx2.shape

(3, 2, 2)

In [13]:
first_nparray.ndim, second_nparr.ndim, matx1.ndim, matx2.ndim

(1, 1, 2, 3)

In [14]:
matx3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]], [[19,20,21], [22,23,24]]])
matx3.ndim

3

In [15]:
first_nparray.dtype, second_nparr.dtype, matx1.dtype, matx2.dtype, matx3.dtype

(dtype('int32'),
 dtype('int32'),
 dtype('float64'),
 dtype('int32'),
 dtype('int32'))

In [16]:
first_nparray.size, second_nparr.size, matx1.size, matx2.size, matx3.size

(3, 3, 9, 12, 24)

In [17]:
type(first_nparray), type(second_nparr), type(matx1), type(matx2), type(matx3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
## create a DataFrame from a NumPy array

import pandas as pd

df = pd.DataFrame(first_nparray)
df1 = pd.DataFrame(second_nparr)
df2 = pd.DataFrame(matx1)


In [19]:
df

0
0  2
1  5
2  8

In [20]:
df1

0
0  7
1  0
2  1

In [21]:
df2
# df2.shape

0    1    2
0  1.0  2.0  2.7
1  3.0  4.0  5.0
2  5.5  6.0  7.0

In [22]:
# df3 = pd.DataFrame(matx2)
matx2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## Creating NumPy Arrays

In [23]:
## below will create and shape a dual-dimensional array.
arr_of_ones = np.ones((3,3), dtype=int, order = 'F')

In [24]:
arr_of_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
arr_of_ones.dtype

dtype('int32')

In [26]:
type(arr_of_ones)

numpy.ndarray

In [27]:
arr_of_ones.dtype

dtype('int32')

In [28]:
arr_of_ones.shape

(3, 3)

In [29]:
arr_of_ones.size

9

In [30]:
arr_of_zeros = np.empty((3,2))

In [31]:
arr_of_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
arr_of_zeros.shape

(3, 2)

In [33]:
multidim_arr = np.full((1,2), [2,3])

In [34]:
multidim_arr

array([[2, 3]])

In [35]:
empty_arr = np.empty((3,3))

In [36]:
empty_arr

array([[1. , 2. , 2.7],
       [3. , 4. , 5. ],
       [5.5, 6. , 7. ]])

In [37]:
empty_arr.dtype

dtype('float64')

In [38]:
empty_arr.shape

(3, 3)

empty_arr.sise

In [39]:
empty_arr.size

9

In [40]:
range_arr = np.arange(1,12)

In [41]:
range_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
range_arr1 = np.arange(0,10,3)

In [43]:
range_arr1

array([0, 3, 6, 9])

In [44]:
rando_arr = np.random.randint(1,14, size=(3,4))

In [45]:
rando_arr

array([[ 7,  9,  3,  8],
       [ 1,  3, 10, 10],
       [ 4,  8, 13,  1]])

In [46]:
rand_arr = np.random.randint(10, size=6)

In [47]:
rand_arr

array([0, 5, 6, 9, 3, 0])

In [48]:
rand_arr1 = np.random.randint(20, size=(4,4), dtype=int)

In [49]:
rand_arr1

array([[11,  4, 18, 15],
       [ 5,  9,  3, 18],
       [19,  2,  8,  7],
       [13,  9,  4,  2]])

In [50]:
rand_arr1.dtype

dtype('int32')

In [51]:
rand_arr1.size

16

In [52]:
## here is another way to create random arrays
rand_arr2 = np.random.random((4,4))

In [53]:
rand_arr2

array([[0.88150317, 0.15314679, 0.16959357, 0.66548786],
       [0.82615831, 0.39371811, 0.8867416 , 0.20896252],
       [0.02056539, 0.04395138, 0.62848727, 0.21026318],
       [0.92508248, 0.27721596, 0.81348956, 0.21355067]])

In [54]:
## yet another random generating technique
rand_arr3 = np.random.rand(3,3)

In [55]:
rand_arr3

array([[0.23591312, 0.97206204, 0.74805973],
       [0.08709214, 0.2435326 , 0.93593104],
       [0.80539268, 0.22804867, 0.91399683]])

In [56]:
# pseudo random numbers
np.random.seed(seed=0)
rand_arr4 = np.random.randint(7, size=(5,3))
rand_arr4

array([[4, 5, 0],
       [3, 3, 3],
       [1, 3, 5],
       [2, 4, 6],
       [0, 0, 4]])

In [57]:
np.random.seed(seed=8)
rand_arr5 = np.random.randint(4, size=(4,3))
rand_arr5

array([[3, 0, 1],
       [1, 1, 2],
       [0, 3, 0],
       [3, 0, 1]])

## different ways of viewing arrays and matrices

In [58]:
np.unique(rand_arr5)

array([0, 1, 2, 3])

In [59]:
rand_arr5[1]

array([1, 1, 2])

In [60]:
rand_arr5[1][2]

2

In [61]:
rand_arr5

array([[3, 0, 1],
       [1, 1, 2],
       [0, 3, 0],
       [3, 0, 1]])

In [62]:
rand_arr5[:2, :2]

array([[3, 0],
       [1, 1]])

In [63]:
## create a 4-dim array
d4 = np.random.randint(7, size=(3,4,6,7))
d4

array([[[[5, 4, 1, 3, 2, 3, 4],
         [5, 1, 5, 5, 2, 3, 2],
         [6, 6, 5, 0, 1, 3, 4],
         [5, 5, 3, 2, 1, 2, 2],
         [6, 1, 5, 5, 6, 1, 3],
         [4, 3, 3, 6, 4, 5, 5]],

        [[0, 4, 4, 2, 0, 5, 2],
         [6, 4, 3, 0, 1, 4, 6],
         [3, 4, 5, 3, 2, 2, 6],
         [6, 6, 2, 6, 1, 6, 0],
         [1, 2, 6, 1, 2, 6, 2],
         [3, 3, 0, 1, 0, 0, 6]],

        [[6, 1, 4, 1, 4, 0, 2],
         [2, 0, 6, 4, 5, 2, 3],
         [3, 3, 3, 6, 4, 0, 1],
         [6, 3, 2, 0, 0, 5, 4],
         [3, 4, 3, 0, 1, 0, 3],
         [2, 1, 5, 2, 6, 6, 3]],

        [[0, 2, 1, 5, 6, 4, 4],
         [5, 1, 3, 5, 5, 4, 0],
         [0, 4, 0, 6, 0, 1, 0],
         [0, 1, 6, 5, 5, 4, 2],
         [2, 5, 6, 2, 4, 2, 6],
         [5, 2, 0, 4, 3, 2, 4]]],


       [[[1, 5, 6, 3, 3, 0, 4],
         [4, 6, 0, 4, 6, 1, 0],
         [5, 3, 4, 0, 2, 3, 2],
         [5, 2, 5, 2, 3, 6, 1],
         [6, 2, 4, 2, 1, 2, 4],
         [2, 4, 6, 3, 1, 1, 1]],

        [[3, 4, 0, 2, 0, 0, 

In [64]:
np.unique(d4)

array([0, 1, 2, 3, 4, 5, 6])

In [65]:
d4[0][0][1]

array([5, 1, 5, 5, 2, 3, 2])

In [66]:
d4[1][1][:1, :4]

array([[3, 4, 0, 2]])

In [67]:
d4[:,:,:,:2]

array([[[[5, 4],
         [5, 1],
         [6, 6],
         [5, 5],
         [6, 1],
         [4, 3]],

        [[0, 4],
         [6, 4],
         [3, 4],
         [6, 6],
         [1, 2],
         [3, 3]],

        [[6, 1],
         [2, 0],
         [3, 3],
         [6, 3],
         [3, 4],
         [2, 1]],

        [[0, 2],
         [5, 1],
         [0, 4],
         [0, 1],
         [2, 5],
         [5, 2]]],


       [[[1, 5],
         [4, 6],
         [5, 3],
         [5, 2],
         [6, 2],
         [2, 4]],

        [[3, 4],
         [5, 2],
         [1, 1],
         [0, 5],
         [6, 1],
         [6, 4]],

        [[6, 4],
         [2, 0],
         [0, 1],
         [2, 5],
         [4, 2],
         [5, 4]],

        [[2, 1],
         [1, 4],
         [5, 3],
         [0, 0],
         [1, 1],
         [2, 3]]],


       [[[1, 6],
         [0, 6],
         [4, 5],
         [1, 3],
         [3, 1],
         [1, 4]],

        [[5, 1],
         [0, 3],
         [5, 2],
         

## Manipulating and Comparing Arrays: the essence of ml

In [68]:
## Arithmetic


vec
# now create an array of 1s
ones = np.ones(3)
vec + ones

array([2., 3., 4.])

In [69]:
vec - ones

array([0., 1., 2.])

In [70]:
vec * ones

array([1., 2., 3.])

In [71]:
vec / ones

array([1., 2., 3.])

In [72]:
vec * first_nparray

array([ 2, 10, 24])

In [73]:
vec *rand_arr5

array([[3, 0, 3],
       [1, 2, 6],
       [0, 6, 0],
       [3, 0, 3]])

In [74]:
vec

array([1, 2, 3])

In [75]:
rand_arr5

array([[3, 0, 1],
       [1, 1, 2],
       [0, 3, 0],
       [3, 0, 1]])

In [76]:
rand_arr5 % 3

array([[0, 0, 1],
       [1, 1, 2],
       [0, 0, 0],
       [0, 0, 1]], dtype=int32)

In [77]:
np.add(vec, first_nparray)

array([ 3,  7, 11])

In [78]:
first_nparray % 2

array([0, 1, 0], dtype=int32)

In [79]:
np.exp(vec)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [80]:
vec

array([1, 2, 3])

In [81]:
np.log(vec)

array([0.        , 0.69314718, 1.09861229])

In [82]:
np.log(first_nparray)

array([0.69314718, 1.60943791, 2.07944154])

In [83]:
first_nparray

array([2, 5, 8])

### Aggregation

In [84]:
sum(vec)

6

In [85]:
vec

array([1, 2, 3])

In [86]:
type(vec)

numpy.ndarray

#### NumPy's aggregation method is np.sum() while python's is sum()

### create a massive numpy array then use python's and numpy's sum methods with the magic function (%timeit) to check which is faster

In [89]:
huge_arr = np.random.random(1000000)
huge_arr.size

1000000

In [90]:
## use both methods with %timeit
%timeit np.sum(huge_arr) # NumPy
%timeit sum(huge_arr)

1.14 ms ± 121 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
88.1 ms ± 2.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [92]:
# 1 millisecond = 1000 miscroseconds
#the outcome below shows that numpy's aggregate function is 726 times faster than python's.
88100 / 121

728.099173553719

In [96]:
#mean of vec
# %timeit mean(huge_arr) #python
%timeit np.mean(huge_arr) #numpy

1.66 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [97]:
%timeit np.max(huge_arr)

573 µs ± 60.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [98]:
%timeit np.min(huge_arr)

709 µs ± 74.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [100]:
#standard deviation is the square root of the variance
%timeit np.std(huge_arr)

7.97 ms ± 645 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [101]:
#variance = measure of the average degree to which each nmumber is different from the mean i.e
    # higher variance = wider range of numbers
    # lower variance = lower range of numbers
np.var(huge_arr)

0.08338018574200581

### standard deviation and variance

In [109]:
high_var_arr = np.array([3,600,900,12000,15000])
low_var_arr = np.array([3,6,9,12,15])

# check the variance of both arrays
np.var(high_var_arr), np.var(low_var_arr)

(41537161.44, 18.0)